# Dependencies
highlighter:      rouge

# Setup
title:            Michael Lai
tagline:          'Blog is Life'
description:      'Data Stuffed'
url:              http://mdlai.github.io
baseurl:          /
permalink:        pretty
logo:             /images/site/house.jpg



author:
  name:           'Michael Lai'
  url:            https://twitter.com/m_d_lai
  avatar:         /images/site/avatar2.jpg
  about:          /about/
  blurb:          "I am a data scientist with a passion for exploring and understanding everything. I love basketball, video games, math, and data."

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mdlai

google_analytics: UA-72303556-1

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: mailto:michael@mdlai.com
  facebook:
  flickr:
  github: https://github.com/mdlai
  instagram:
  linkedin: https://www.linkedin.com/in/michael-lai-52828a71
  pinterest:
  rss: /atom.xml # just type anything here for a working RSS icon
  twitter: https://twitter.com/m_d_lai
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
