# Dependencies
highlighter:      rouge

# Setup
title:            Michael Lai
tagline:          'Blog is Life'
description:      'Data Stuff'
url:              http://mdlai.github.io
baseurl:          /
permalink:        pretty
logo:             /images/house.jpg



author:
  name:           'Michael Lai'
  url:            https://twitter.com/m_d_lai
  avatar:         /images/house.jpg
  about:          /about/
  blurb:          I am a data scientist with a passion for exploring and understanding everything.

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mdlai

google_analytics: UA-72303556-1

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: michael@mdlai.com
  facebook:
  flickr:
  github: mdlai
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: m_d_lai
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
